# Copyright (c) 2023-2026 Chris (boreddevnl)
# This software is released under the GNU General Public License v3.0. See LICENSE file for details.
# This header needs to maintain in any file it is present in, as per the GPL license terms.

timeout: 3
verbose: yes

${WALLPAPER_PATH}=boot():/splash.jpg
wallpaper: ${WALLPAPER_PATH}
wallpaper_style: centered
backdrop: 000000

/BoredOS
    protocol: limine
    path: boot():/boredos.elf
    cmdline: -v
